[Service]
User=kartofel
Group=kartofel
Environment="OLLAMA_MODELS=/home/kartofel/.ollama/models"
Environment="HOME=/home/kartofel"
Environment="OLLAMA_FLASH_ATTENTION=1"
Environment="OLLAMA_KV_CACHE_TYPE=q4_0"
Environment="OLLAMA_NUM_BATCH=1024"
